In [3]:
#User defined function
def number():
    print('hello')
    


In [4]:
number()

hello


In [5]:
for i in range(5):
    number()

hello
hello
hello
hello
hello


In [6]:
#return

In [8]:
def add():
    a=10
    b=20
    c=a+b
    return c

In [10]:
v=add()
print(v)

30


In [12]:
#function with parameter with return type

def even_odd(num):
    if num%2==0:
        return 'even'
    else:
        return 'odd'

In [14]:
out=even_odd(5)
print(out)

odd


In [18]:
#function without parameter without return type

def even_odd():
    num=int(input('enter a num'))
    if num%2==0:
        print('even')
    else:
        print('odd')

In [21]:
out=even_odd()
print(out)

enter a num12
even
None


In [22]:
#function without parameter with return type

def even_odd():
    num=int(input('enter a num'))
    if num%2==0:
        return 'even'
    else:
        return 'odd'

In [23]:
out=even_odd()
print(out)

enter a num123
odd


In [24]:
def data(name,age):
    print(f'my name is {name} and iam {age}')

In [27]:
data('abc',22) #default arguments

my name is abc and iam 22


In [28]:
data(age=22,name='xyz') #keywords

my name is xyz and iam 22


In [ ]:
#variable length args

In [36]:
def nums(one,two,*a):
    print(one,two)
    print(a)

In [39]:
nums(1,2,'num','even',999)

1 2
('num', 'even', 999)


In [40]:
#** variable length keyword args (**kwargs)

In [41]:
def data(**k):
    print(k)

In [42]:
data(name='abc',age=22)

{'name': 'abc', 'age': 22}


In [3]:
#generator function

def numbers(num):
    for i in range(num):
        yield i
    
    

In [5]:
o=numbers(5)
print(o)
print(tuple(o))

<generator object numbers at 0x000001934F593F20>
(0, 1, 2, 3, 4)


In [57]:
#local and global

x=10
x=30
def num():
    x=20
    x=99
    print(x)
    
print(x)
num()

30
99


In [45]:
# Python program to illustrate
# nested functions
def outerFunction(text):
    print(text+" "+'python')

    def innerFunction():
        print(text)

    innerFunction()



outerFunction('Hey!')


Hey! python
Hey!


In [59]:
def calculate():
    num = 1
    def inner_func():
        nonlocal num
        num += 2
        return num
    return inner_func

# call the outer function
odd = calculate()

# call the inner function
print(odd())
print(odd())
print(odd())

# call the outer function again
odd2 = calculate()
print(odd2())

3
5
7
3


In [6]:
def my_decorator(func):
    def wrapper():
        print("Something before the function.")
        func()
        print("Something after the function.")
        func()
    return wrapper

# Applying the decorator
@my_decorator
def say_hello():
    print("Hello!")

say_hello()

Something before the function.
Hello!
Something after the function.
Hello!


In [6]:
o=lambda x,y,op:(lambda a,b:a+b if op=='add' else
                            a-b if op=='sub' else
                            a*b if op=='mul' else
                            None)(x,y)

print(o(2,3,'add'))
print(o(4,8,'sub'))
print(o(5,5,'mul'))

5
-4
25


In [7]:
n=10
for i in range(1,11):
    print(f'{n} X {i} = {n*i}')

10 X 1 = 10
10 X 2 = 20
10 X 3 = 30
10 X 4 = 40
10 X 5 = 50
10 X 6 = 60
10 X 7 = 70
10 X 8 = 80
10 X 9 = 90
10 X 10 = 100


In [9]:
out=lambda n:[print(f'{n} X {i} = {n*i}') for i in range(1,11) ]
out(8)

8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
8 X 10 = 80


[None, None, None, None, None, None, None, None, None, None]

In [10]:
l=[3,4,5,6,7,7]


for r in l:
    o=lambda i:3.14*i*i
    print(o(r))

28.259999999999998
50.24
78.5
113.03999999999999
153.86
153.86


In [15]:
#map()

l=[1,2,35,7,8]
o=list(map(lambda r:3.14*r*r,l))
print(o)

[3.14, 12.56, 3846.5, 153.86, 200.96]


In [17]:
def area(r):
    a=3.14*r*r
    return a

In [19]:
o=list(map(area,l))
print(o)

[3.14, 12.56, 3846.5, 153.86, 200.96]


In [ ]:
f=[99.1,101.5,88,103]

In [ ]:
#sort a dict by values
d={'A':30,'B':25,'c':35,'D':28}

In [2]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray


# load the image and convert into
# numpy array
img = Image.open('sample.png')

# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = asarray(img)

# <class 'numpy.ndarray'>
print(type(numpydata))

# shape
print(numpydata.shape)

print(numpydata)


<class 'numpy.ndarray'>
(200, 200, 4)
[[[233 233 233 229]
  [233 233 233 242]
  [233 233 233 242]
  ...
  [233 233 233 242]
  [233 233 233 242]
  [233 233 233 229]]

 [[233 233 233 255]
  [233 233 233 255]
  [233 233 233 255]
  ...
  [233 233 233 255]
  [233 233 233 255]
  [233 233 233 255]]

 [[233 233 233 242]
  [233 233 233 255]
  [233 233 233 255]
  ...
  [233 233 233 255]
  [233 233 233 255]
  [233 233 233 242]]

 ...

 [[233 233 233 242]
  [233 233 233 255]
  [233 233 233 255]
  ...
  [233 233 233 255]
  [233 233 233 255]
  [233 233 233 242]]

 [[233 233 233 255]
  [233 233 233 255]
  [233 233 233 255]
  ...
  [233 233 233 255]
  [233 233 233 255]
  [233 233 233 255]]

 [[233 233 233 229]
  [233 233 233 242]
  [233 233 233 242]
  ...
  [233 233 233 242]
  [233 233 233 242]
  [233 233 233 229]]]


In [1]:
from PIL import Image
import numpy as np

# Load image and convert to NumPy array
img = Image.open('sample.png')
img_array = np.array(img)
img.show()

In [3]:
# Calculate the grayscale value by averaging the RGB channels
gray_image = img_array.mean(axis=2).astype(np.uint8)

# Convert back to an image for viewing
gray_img = Image.fromarray(gray_image)
gray_img.show()  # This opens the grayscale image


In [4]:
# Horizontal flip
#flipped_horizontal = img_array[:, ::-1, :]

# Vertical flip
flipped_vertical = img_array[::-1, :, :]

# Show flipped images
#Image.fromarray(flipped_horizontal).show()  # Horizontal flip
Image.fromarray(flipped_vertical).show()    # Vertical flip


In [5]:
# Rotate image 90 degrees
rotated_image = np.rot90(img_array)

# Show the rotated image
Image.fromarray(rotated_image).show()


In [6]:
# Define a simple 3x3 mean filter
kernel = np.ones((3, 3)) / 9

# Pad the image to handle borders
padded_img = np.pad(img_array, ((1, 1), (1, 1), (0, 0)), mode='edge')

# Apply mean filter to each channel
blurred_img = np.zeros_like(img_array)
for channel in range(3):  # For each color channel
    for i in range(img_array.shape[0]):
        for j in range(img_array.shape[1]):
            blurred_img[i, j, channel] = (padded_img[i:i+3, j:j+3, channel] * kernel).sum()

# Show the blurred image
Image.fromarray(blurred_img).show()


In [7]:
# Convert to grayscale
gray_image = img_array.mean(axis=2).astype(np.uint8)

# Increase brightness
brightened_image = np.clip(gray_image * 1.3, 0, 255).astype(np.uint8)

# Horizontal flip
flipped_image = brightened_image[:, ::-1]

# Show the final processed image

Image.fromarray(flipped_image).show()
