In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]
print(my_list)
print(type(my_list))

[1, 2, 3]
<class 'list'>


In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
n=np.array(my_matrix)
#print(n.shape)
#print(n[0][1:])
print(n)
print(n[:,1:]) #row and col

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
my_li=['apple','orange','grape']
np.array(my_li)

array(['apple', 'orange', 'grape'], dtype='<U6')

In [ ]:
li=[['apple','orange','grape'],['tomato','berry','greens'],['carrot','beans','onion']]
np.array(li)

array([['apple', 'orange', 'grape'],
       ['tomato', 'berry', 'greens'],
       ['carrot', 'beans', 'onion']], dtype='<U6')

In [ ]:
n=[1,2,'apple',3.14]
n1=np.array(n)
print(n1)

['1' '2' 'apple' '3.14']


In [ ]:
print(type(n1[0]))

<class 'numpy.str_'>


In [ ]:
n=[1,2,3.14]
n1=np.array(n)
print(n1)
print(type(n1[0]))

[1.   2.   3.14]
<class 'numpy.float64'>


In [ ]:
n=[1,2,3.14,True,False]
n1=np.array(n)
print(n1)
print(type(n1[0]))

[1.   2.   3.14 1.   0.  ]
<class 'numpy.float64'>


In [ ]:
n=[1,2,True,False]
n1=np.array(n)
print(n1[0])
print(type(n1[0]))

1
<class 'numpy.int64'>


In [ ]:
n2=[1,2,3,4,5]
my_n2=np.array(n2)
print(my_n2)
my_n2_with_commas=my_n2.tolist()
print(my_n2_with_commas)
print(type(my_n2_with_commas))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
n2=[[1,2,3],[4,5,6],[7,8,9]]
my_n2=np.array(n2)
my_n2_with_commas=list(my_n2)
print(my_n2_with_commas)
print(type(my_n2_with_commas))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>


In [ ]:
# Built-in Methods
# There are lots of built-in ways to generate Arrays

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# zeros and ones
# Generate arrays of zeros or ones

np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# linspace
# Return evenly spaced numbers over a specified interval.

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
# eye
# Creates an identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Random
# Numpy also has lots of ways to create random number arrays:

np.random.rand(2)

array([0.99664024, 0.37439931])

In [ ]:
np.random.rand(5,5)

array([[0.61932663, 0.3884042 , 0.38709646, 0.67612842, 0.76894244],
       [0.09335672, 0.22108513, 0.54501022, 0.55825535, 0.03728635],
       [0.0196755 , 0.72299105, 0.80732541, 0.70233955, 0.46838844],
       [0.71181909, 0.54529427, 0.81919238, 0.79151204, 0.59848148],
       [0.48809056, 0.45955554, 0.42511675, 0.84661365, 0.98753634]])

In [ ]:
# randn
# Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

np.random.randn(2)

array([0.47429987, 1.34303117])

In [ ]:
np.random.randn(5,5)

array([[-1.32665678, -0.94378209,  0.21463434,  0.84238761,  0.68740954],
       [ 0.1326357 ,  0.30345894, -0.84992356,  0.37608249, -1.08279677],
       [-0.21761193, -0.5316018 ,  1.3576246 , -0.76152746,  0.81254397],
       [ 1.486469  , -0.41715823, -1.93515079, -0.96628654, -0.95013036],
       [ 0.60475784, -1.2441336 , -1.09974829, -1.37155851, -0.71936195]])

In [ ]:
# randint
# Return random integers from low (inclusive) to high (exclusive).

np.random.randint(1,100)

95

In [ ]:
np.random.randint(1,100,10)

array([91, 93, 93, 84, 57, 22, 72, 49, 85, 33])

In [ ]:
np.random.randint(1,100, size=(3,3))

array([[ 4, 47, 26],
       [ 4, 92, 17],
       [94, 83, 12]])

In [ ]:
# Array Attributes and Methods
# some useful attributes and methods or an array:

arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[14 43  7 14 18 21  9  2  0 45]


In [ ]:
# Reshape
# Returns an array containing the same data with a new shape.

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#max,min,argmax,argmin

ranarr

array([14, 43,  7, 14, 18, 21,  9,  2,  0, 45])

In [ ]:
ranarr.max()

45

In [ ]:
ranarr.argmax()

9

In [ ]:
ranarr.min()

0

In [ ]:
ranarr.argmin()

8

In [ ]:
# Shape
arr.shape

(25,)

In [ ]:
# puts two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

In [ ]:
#NumPy Indexing and Selection
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
# Broadcasting

#Setting a value with index range (Broadcasting)
arr[0:5]=100


arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)


arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Slices
slice_of_arr = arr[0:6]


slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:]=99


slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#Indexing a 2D array (matrices)

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
print(arr_2d[1])
print(arr_2d[1][0])


[20 25 30]
20


In [ ]:
##Shape (2,2) from top right corner
print(arr_2d[:2,1:])

[[10 15]
 [25 30]]


In [ ]:
print(arr_2d[:2])

[[ 5 10 15]
 [20 25 30]]


In [ ]:
print(arr_2d[:,1:])

[[10 15]
 [25 30]
 [40 45]]


In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))
print(arr2d)
#Length of array
arr_length = arr2d.shape[1]

print(arr_length)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
10


In [ ]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [ ]:
arr3=np.random.randint(1,1000, size=(10,10))
arr3

array([[341, 750, 546, 745, 622, 189, 368, 912, 269, 667],
       [963, 796,  50, 409, 677, 963, 854, 204, 884, 893],
       [628, 272, 964, 377, 204, 826, 555, 542, 845, 830],
       [ 46, 853, 697, 523, 342, 586, 928, 223, 931, 393],
       [585, 234, 773, 430, 992, 843, 220, 170, 217, 121],
       [205, 913, 698,  30, 531, 779, 505, 216, 197, 560],
       [210, 410, 554, 647, 904, 804, 189,  47, 171, 369],
       [594, 725, 523, 716, 828, 613, 321, 619, 905, 482],
       [585, 370, 908, 315,  86, 560, 399, 720, 266, 426],
       [267, 158, 598, 596,  50, 706,  56, 648, 751, 546]])

In [ ]:
arr3[[6,4,2,7]]

array([[210, 410, 554, 647, 904, 804, 189,  47, 171, 369],
       [585, 234, 773, 430, 992, 843, 220, 170, 217, 121],
       [628, 272, 964, 377, 204, 826, 555, 542, 845, 830],
       [594, 725, 523, 716, 828, 613, 321, 619, 905, 482]])

In [ ]:
lis=[1,2,3,4]
lis+lis

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
#array operations
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan

arr/arr

<ipython-input-68-18320eff7d4f>:4: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

<ipython-input-69-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
# Universal Array Functions
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-74-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
# dimension array

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
x4 = np.random.randint(10, size=(3,3,4,5))  # Four-dimensional array

In [ ]:
x1

array([0, 3, 5, 2, 1, 7])

In [ ]:
x2

array([[9, 9, 9, 7],
       [1, 0, 4, 7],
       [4, 4, 9, 9]])

In [ ]:
x3

array([[[4, 1, 7, 2, 6],
        [6, 9, 9, 4, 0],
        [9, 2, 8, 7, 4],
        [9, 5, 5, 4, 2]],

       [[1, 2, 1, 2, 6],
        [1, 0, 7, 8, 1],
        [9, 8, 7, 1, 2],
        [5, 0, 2, 4, 9]],

       [[8, 0, 9, 6, 5],
        [4, 9, 1, 4, 3],
        [0, 1, 6, 7, 4],
        [3, 4, 6, 3, 3]]])

In [ ]:
x4

array([[[[6, 9, 3, 8, 1],
         [9, 9, 4, 2, 7],
         [8, 1, 5, 1, 8],
         [8, 8, 1, 2, 1]],

        [[3, 3, 1, 4, 4],
         [5, 2, 1, 3, 2],
         [5, 3, 2, 2, 3],
         [4, 5, 9, 0, 0]],

        [[6, 9, 8, 2, 3],
         [9, 4, 1, 8, 1],
         [1, 6, 3, 6, 5],
         [4, 0, 6, 2, 6]]],


       [[[2, 7, 4, 8, 3],
         [8, 8, 4, 5, 8],
         [5, 9, 3, 4, 3],
         [1, 2, 2, 1, 0]],

        [[0, 1, 2, 6, 5],
         [1, 4, 0, 2, 8],
         [1, 3, 5, 7, 3],
         [3, 3, 9, 3, 2]],

        [[3, 9, 3, 3, 9],
         [6, 9, 5, 4, 8],
         [9, 5, 1, 1, 9],
         [7, 5, 1, 2, 9]]],


       [[[5, 0, 0, 8, 6],
         [2, 8, 0, 6, 5],
         [8, 6, 4, 4, 5],
         [1, 1, 2, 9, 8]],

        [[5, 3, 4, 6, 1],
         [0, 5, 1, 4, 1],
         [3, 2, 7, 1, 7],
         [2, 8, 3, 1, 6]],

        [[3, 2, 8, 9, 6],
         [0, 4, 2, 5, 1],
         [6, 3, 9, 9, 8],
         [4, 5, 4, 7, 0]]]])

In [ ]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6


In [ ]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print("x1 ndim: ", x4.ndim)
print("x1 shape:", x4.shape)
print("x1 size: ", x4.size)

x1 ndim:  4
x1 shape: (3, 3, 4, 5)
x1 size:  180


In [ ]:
# Concatenation of arrays

x = np.array((1, 2, 3))
y = np.array((3, 2, 1))
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
# can also concatenate more than two arrays at once:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [ ]:
#It can also be used for two-dimensional arrays

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:


# create a 3D array
a = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8]],
              
              [[9, 10, 11, 12],
               [13, 14, 15, 16]],
              
              [[17, 18, 19, 20],
               [21, 22, 23, 24]]])

# split the array into two 2D arrays along the third axis
b, c = np.dsplit(a, 2)

# print the resulting arrays
print(b)

print('----------')

print(c)


[[[ 1  2]
  [ 5  6]]

 [[ 9 10]
  [13 14]]

 [[17 18]
  [21 22]]]
----------
[[[ 3  4]
  [ 7  8]]

 [[11 12]
  [15 16]]

 [[19 20]
  [23 24]]]


In [ ]:
b=np.random.randint(0, 10, (3,4))
print(b)
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))

[[7 3 4 4]
 [1 6 3 6]
 [6 7 0 1]]
Column sums: [14 16  7 11]
Row sums: [18 16 14]


Note that most of the aggregation functions in NumPy have corresponding methods. In addition, Python language has builtin functions `sum`, `min`, `max`, `any`, and `all` for sequences. Make sure you don't accidentally use these for arrays, since they may have slightly different semantics, and they will be significantly slower than NumPy's functions and methods.
Python function	NumPy function	NumPy method
sum	np.sum	a.sum
-	np.prod	a.prod
-	np.mean	a.mean
-	np.std	a.std
-	np.var	a.var
min	np.min	a.min
max	np.max	a.max
-	np.argmin	a.argmin
-	np.argmax	a.argmax
-	np.median	-
-	np.percentile	-
any	np.any	a.any
all	np.all	a.all


In [ ]:


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

cumsum_result = np.cumsum(arr, axis=0)
cumprod_result = np.cumprod(arr, axis=1)

print(arr)

print("Cumulative sum along rows:\n", cumsum_result)
print("Cumulative product along columns:\n", cumprod_result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Cumulative sum along rows:
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
Cumulative product along columns:
 [[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


In [ ]:


# create a 3x3 numpy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# access the second column
col = arr[:, 1]
#arr[0][0]
col1=arr[:,2]

print(col)

print()

print(col1)


[2 5 8]

[3 6 9]


In [ ]:


my_dict = {'a': 1, 'b': 2, 'c': 3}

my_array = np.array(list(my_dict.values()))

print(my_array)


[1 2 3]


In [ ]:
import numpy as np

my_dict = {'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}

my_array = np.array([my_dict[key] for key in my_dict])

print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

arr = np.array([[1, 2,5], [3, 4,6]])

# Pad the array with zeros
padded_arr = np.pad(arr, ((2, 2),(0,0)), mode='constant')

print(padded_arr)


[[0 0 0]
 [0 0 0]
 [1 2 5]
 [3 4 6]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr = np.array([[1, 2], [3, 4]])

# Pad the array with zeros
padded_arr = np.pad(arr, ((2, 2), (2, 2)), mode='edge')

print(padded_arr)

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]
 [3 3 3 4 4 4]]


In [ ]:
arr = np.array([['a', 'b'], [3, 4]])

# Pad the array with zeros
padded_arr = np.pad(arr, ((2, 2), (2, 2)), mode='symmetric')

print(padded_arr)

[['4' '3' '3' '4' '4' '3']
 ['b' 'a' 'a' 'b' 'b' 'a']
 ['b' 'a' 'a' 'b' 'b' 'a']
 ['4' '3' '3' '4' '4' '3']
 ['4' '3' '3' '4' '4' '3']
 ['b' 'a' 'a' 'b' 'b' 'a']]


In [ ]:
import numpy as np

# Create an array
a = np.array([1, 2, 3, 4, 5,6])

# Create a boolean array based on a condition
b = a > 2
print(b)
# Use numpy.where() to select values based on the condition
c = np.where(a>2, a, 999)

print(c)
# Output: [0 0 3 4 5]


[False False  True  True  True  True]
[999 999   3   4   5   6]


In [ ]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Use numpy.where() to get the indices of elements greater than 3
indices = np.where(arr > 3)

# Print the indices
print(indices)


(array([3, 4]),)


In [ ]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
print(b)


[1 2 3 4 5 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.insert(a, 1, [4, 5])
print(b)

[1 4 5 2 3]


In [ ]:
a = np.array([1, 2, 3])
b = np.delete(a, 1)
print(b)

[1 3]


In [ ]:
#sort
arr = np.array([3, 1, 5, 2, 4])
arr.sort()
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([[4,3, 2], [3,5, 1]])
arr.sort(axis=0)
print(arr)

[[3 3 1]
 [4 5 2]]


In [ ]:
arr = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
arr.sort(axis=1)
print(arr)

[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [ ]:

a=True,False,None
# create a 2D array
arr = np.array([[1, 2], [3, 4]])
print(arr)
print()

# add a new dimension at position 1
new_arr = np.expand_dims(arr, axis=1)

print(new_arr.shape) # prints (2, 1, 2)
print()
print(new_arr)

[[1 2]
 [3 4]]

(2, 1, 2)

[[[1 2]]

 [[3 4]]]


In [ ]:
# create a 2D array
arr = np.array([[1, 2], [3, 4]])
print(arr)
print()

# add a new dimension at position 1
new_arr = np.expand_dims(arr, 1)

print(new_arr.shape) # prints (2, 1, 2)
print()
print(new_arr)

[[1 2]
 [3 4]]

(2, 1, 2)

[[[1 2]]

 [[3 4]]]


In [ ]:
#isnan
a = np.array([1, np.nan, 3, np.nan])
result = np.isnan(a)
print(result)


[False  True False  True]


In [ ]:
arr = np.array([[4,np.nan , 6], [7, 8, 9], [1, np.nan, 3]])
result = np.isnan(arr)
print(result)


[[False  True False]
 [False False False]
 [False  True False]]


In [ ]:
arr = np.arange(0,10)
print(arr)
div=arr/arr
print(div)
r=np.isnan(div)
r

[0 1 2 3 4 5 6 7 8 9]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-16-128fb25bdcec>:3: RuntimeWarning: invalid value encountered in true_divide
  div=arr/arr


array([ True, False, False, False, False, False, False, False, False,
       False])

In [ ]:


arr = np.array([1, 2, np.inf, -np.inf, 5])
np.isinf(arr)

array([False, False,  True,  True, False])

In [ ]:
arr = np.arange(0,10)
div=1/arr
r=np.isinf(div)
r

<ipython-input-31-5d5f6f348ba9>:2: RuntimeWarning: divide by zero encountered in true_divide
  div=1/arr


array([ True, False, False, False, False, False, False, False, False,
       False])

In [ ]:
arr = np.array([1.1, 2.5, 3.7, -4.3])
ceiled = np.ceil(arr)
print(ceiled)

[ 2.  3.  4. -4.]


In [ ]:
arr = np.array([1.1, 2.5, 3.7, -4.3])
floored = np.floor(arr)
print(floored)

[ 1.  2.  3. -5.]


In [ ]:
import numpy as np
arr = np.array([1.2231, 2.567, 3.7698, -4.3987])
rounded = np.round(arr, decimals=2)
print(rounded)

[ 1.22  2.57  3.77 -4.4 ]


In [ ]:
import numpy as np

# Create an array with some zeros and non-zeros
arr = np.array([1, 0, 3, 0, 5])

# Check if any elements are non-zero
print(np.any(arr))  # True

# Check if all elements are non-zero
print(np.all(arr))  # False

# Create a boolean array
bool_arr = np.array([True, True, False, True, False])

# Check if any elements are True
print(np.any(bool_arr))  # True

# Check if all elements are True
print(np.all(bool_arr))  # False


True
False
True
False


In [ ]:
import numpy as np

# Creating a 3x3 random matrix
arr = np.random.randint(1, 10, (3, 3))
print("Original Array:\n", arr)

# Indexing and Slicing
print("First Row:\n", arr[0])
print("Last Column:\n", arr[:, -1])
print("Middle Element:\n", arr[1, 1])

# Reshaping
arr_1d = arr.reshape(9)
arr_2d = arr.reshape(3, -1)
arr_3d = arr.reshape(3, 3, 1)
print("Reshaped 1D:\n", arr_1d)
print("Reshaped 2D:\n", arr_2d)
print("Reshaped 3D:\n", arr_3d)

# Element-wise Operations
arr_add = arr + 2
arr_sub = arr - 2
arr_mul = arr * 2
arr_div = arr / 2
arr_pow = arr ** 2
print("Addition:\n", arr_add)
print("Subtraction:\n", arr_sub)
print("Multiplication:\n", arr_mul)
print("Division:\n", arr_div)
print("Power:\n", arr_pow)

# Statistical Functions
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
var = np.var(arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", var)

# Sorting
arr_sorted = np.sort(arr, axis=None)
print("Sorted Array:\n", arr_sorted)

# Other Functions
arr_sum = np.sum(arr)
arr_prod = np.prod(arr)
arr_min = np.min(arr)
arr_max = np.max(arr)
print("Sum:", arr_sum)
print("Product:", arr_prod)
print("Minimum Value:", arr_min)
print("Maximum Value:", arr_max)


Original Array:
 [[4 3 8]
 [4 5 4]
 [5 8 8]]
First Row:
 [4 3 8]
Last Column:
 [8 4 8]
Middle Element:
 5
Reshaped 1D:
 [4 3 8 4 5 4 5 8 8]
Reshaped 2D:
 [[4 3 8]
 [4 5 4]
 [5 8 8]]
Reshaped 3D:
 [[[4]
  [3]
  [8]]

 [[4]
  [5]
  [4]]

 [[5]
  [8]
  [8]]]
Addition:
 [[ 6  5 10]
 [ 6  7  6]
 [ 7 10 10]]
Subtraction:
 [[2 1 6]
 [2 3 2]
 [3 6 6]]
Multiplication:
 [[ 8  6 16]
 [ 8 10  8]
 [10 16 16]]
Division:
 [[2.  1.5 4. ]
 [2.  2.5 2. ]
 [2.5 4.  4. ]]
Power:
 [[16  9 64]
 [16 25 16]
 [25 64 64]]
Mean: 5.444444444444445
Median: 5.0
Standard Deviation: 1.892154040658489
Variance: 3.580246913580247
Sorted Array:
 [3 4 4 4 5 5 8 8 8]
Sum: 49
Product: 2457600
Minimum Value: 3
Maximum Value: 8


Some of the most frequently used functions in numpy are:

1.np.array(): to create numpy arrays from Python lists or other sequences.

2.np.arange(): to create an array with regularly spaced values.

3.np.zeros(): to create an array of all zeros.

4.np.ones(): to create an array of all ones.

5.np.linspace(): to create an array of evenly spaced values between two endpoints.

6.np.random.rand(): to generate an array of random numbers between 0 and 1.

7.np.random.randn(): to generate an array of random numbers from a standard normal distribution.

8.np.min(): to find the minimum value in an array.

9.np.max(): to find the maximum value in an array.

10.np.mean(): to find the mean of an array.

11.np.median(): to find the median of an array.

12.np.sum(): to find the sum of an array.

13.np.prod(): to find the product of an array.

14.np.transpose(): to transpose an array.

15.np.dot(): to perform dot product of two arrays.

16.np.linalg.inv(): to find the inverse of a matrix.

17.np.linalg.det(): to find the determinant of a matrix.

18.np.where(): to find the indices where a condition is true in an array.





In [ ]:
import numpy as np

# create an input array
x = np.array([1.2, 2.4, 3.6, 4.8])

# create a sequence of scalars as bins
bins = [1, 2, 3, 4, 5]

# use digitize to get the indices of the bins to which each value belongs
result = np.digitize(x, bins)

# print the result
print(result)

[1 2 3 4]
